### ISSUE TITLE
Could not pass event PLAYER_CHAT to SpamHammer

### ISSUE THREAD

**Issue by SniperXPX** [dumptruckman/SpamHammer#1]
Ever since I upgraded from 1.4 to 1.7a these errors are thrown whenever someone chats in the server:

16:57:30 [SEVERE] Could not pass event PLAYER_CHAT to SpamHammer
java.lang.NoSuchMethodError: org.bukkit.entity.Player.hasPermission(Ljava/lang/String;)Z
        at com.dumptruckman.spamhammer.listeners.SpamHammerPlayerListener.onPlayerChat(SpamHammerPlayerListener.java:29)
        at org.bukkit.plugin.java.JavaPluginLoader$6.execute(JavaPluginLoader.java:279)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:321)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:681)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:669)
        at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:84)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:451)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:361)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by SniperXPX** [comment]
if possible, could you provide 1.4 version download?

**Comment by dumptruckman** [comment]
You must use CB 1000+.

If you're unable to upgrade, let me know.

**Comment by SniperXPX** [comment]
I do not want to upgrade to the latest CB as the latest version of minecraft has a bug where tile entities are deleted randomly in some chunks causing chest contents and signs etc to be erased and left blank.

**Comment by dumptruckman** [comment]
I will see what I can do.  I could just alter 1.7a have a "use permissions" config.

**Comment by dumptruckman** [comment]
Okay, 1.7b is released, added a setting to disable use of permissions.  This will put it in "op mode".  Only ops can use the commands.  Only ops will be ignored by the plugin.

**Comment by SniperXPX** [comment]
Okay great, thanks!
